### PR TITLE
Fix broken FB_REFERENCE_IMAGE_DIR preprocessor macro

### LINKED ISSUE #209: Setting FB_REFERENCE_IMAGE_DIR as a preprocessor macro broken in 2.1.4
[This](https://github.com/facebook/ios-snapshot-test-case/commit/6a3f71fd69b7fab9d7aced48100199c104ac1719) change broke the ability to set `FB_REFERENCE_IMAGE_DIR` as a preprocessor macro. By moving all that code from a macro to  'debuggable code', the preprocessor step now always uses the default `""` as here:

```
#ifndef FB_REFERENCE_IMAGE_DIR
#define FB_REFERENCE_IMAGE_DIR ""
#endif
```

### PR DESCRIPTION
**Pull request by alanzeino**
[A change](https://github.com/facebook/ios-snapshot-test-case/commit/6a3f71fd69b7fab9d7aced48100199c104ac1719) was made that converted the bulk of what was previously a macro, to actual code. The problem with that, was it moved the tricky use of FB_REFERENCE_IMAGE_DIR out of the macro, so setting `FB_REFERENCE_IMAGE_DIR` in your preprocessor macros yourself no longer worked.

It used to work by replacing instances of `FB_REFERENCE_IMAGE_DIR` in the preprocessor step with the one you could set in your preprocessor macros, but that doesn't seem to work unless you're in a #define.

Fixes #209

### CODE REVIEW

File: FBSnapshotTestCase/FBSnapshotTestCase.m [hunk 1]
```diff
@@ -69,11 +69,12 @@ - (NSString *)snapshotVerifyViewOrLayer:(id)viewOrLayer
                              identifier:(NSString *)identifier
                                suffixes:(NSOrderedSet *)suffixes
                               tolerance:(CGFloat)tolerance
+              defaultReferenceDirectory:(NSString *)defaultReferenceDirectory
```
Comment (nscoding) [inline FBSnapshotTestCase/FBSnapshotTestCase.m]: can you document this parameter?

Comment (alanzeino) [inline FBSnapshotTestCase/FBSnapshotTestCase.m]: Done!

**Comment by alanzeino** [comment]
Updated the original commit with documentation.

**Comment by brentleyjones** [comment]
Bump

**Comment by ceeK** [comment]
@nscoding Can this be merged?

**Comment by garnett** [comment]
Could someone merge it, please

**Comment by garnett** [comment]
Thank you @nscoding! Could you please do a new release in Cocoapods? The last one is rather dated at the moment.

**Comment by alanzeino** [comment]
@garnett change your Podfile to use `:git` until they make a new version
